[build]
  command = "npm run build"
  publish = "dist"

# Clean URLs → actual HTML files
[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-and-conditions.html"
  status = 200

[[redirects]]
  from = "/terms-of-service/"
  to = "/terms-and-conditions.html"
  status = 200

# SPA fallback LAST (for your React app’s routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
