[build]
  publish = "."

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-and-conditions.html"
  status = 200

[[redirects]]
  from = "/terms-and-conditions"
  to = "/terms-and-conditions.html"
  status = 200